/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGALLEGROCL
#define SWIGALLEGROCL
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif



#ifdef __cplusplus
#  define EXTERN   extern "C"
#else
#  define EXTERN   extern
#endif

#define EXPORT   EXTERN SWIGEXPORT

typedef void *__SWIGACL_FwdReference;

#include <string.h>
#include <stdlib.h>


#include "4ti2/4ti2.h"



struct _4ti2_state {};
struct _4ti2_matrix {};


EXPORT struct _4ti2_state *ACL___new__4ti2_state__SWIG_0 () {
  struct _4ti2_state *lresult = (struct _4ti2_state *)0 ;
  struct _4ti2_state *result = 0 ;
  
  result = (struct _4ti2_state *)calloc(1, sizeof(struct _4ti2_state));
  lresult = result;
  return lresult;
}


EXPORT void ACL___delete__4ti2_state__SWIG_0 (struct _4ti2_state *larg1) {
  struct _4ti2_state *arg1 = (struct _4ti2_state *) 0 ;
  
  arg1 = larg1;
  free((char *) arg1);
}


EXPORT struct _4ti2_matrix *ACL___new__4ti2_matrix__SWIG_0 () {
  struct _4ti2_matrix *lresult = (struct _4ti2_matrix *)0 ;
  struct _4ti2_matrix *result = 0 ;
  
  result = (struct _4ti2_matrix *)calloc(1, sizeof(struct _4ti2_matrix));
  lresult = result;
  return lresult;
}


EXPORT void ACL___delete__4ti2_matrix__SWIG_0 (struct _4ti2_matrix *larg1) {
  struct _4ti2_matrix *arg1 = (struct _4ti2_matrix *) 0 ;
  
  arg1 = larg1;
  free((char *) arg1);
}


EXPORT int const ACL_ENUM____4ti2_PREC_INT_32__SWIG_0;
int const ACL_ENUM____4ti2_PREC_INT_32__SWIG_0 = _4ti2_PREC_INT_32;
EXPORT int const ACL_ENUM____4ti2_PREC_INT_64__SWIG_0;
int const ACL_ENUM____4ti2_PREC_INT_64__SWIG_0 = _4ti2_PREC_INT_64;
EXPORT int const ACL_ENUM____4ti2_PREC_INT_ARB__SWIG_0;
int const ACL_ENUM____4ti2_PREC_INT_ARB__SWIG_0 = _4ti2_PREC_INT_ARB;
EXPORT int const ACL_ENUM____4ti2_FR__SWIG_0;
int const ACL_ENUM____4ti2_FR__SWIG_0 = _4ti2_FR;
EXPORT int const ACL_ENUM____4ti2_LB__SWIG_0;
int const ACL_ENUM____4ti2_LB__SWIG_0 = _4ti2_LB;
EXPORT int const ACL_ENUM____4ti2_UB__SWIG_0;
int const ACL_ENUM____4ti2_UB__SWIG_0 = _4ti2_UB;
EXPORT int const ACL_ENUM____4ti2_DB__SWIG_0;
int const ACL_ENUM____4ti2_DB__SWIG_0 = _4ti2_DB;
EXPORT int const ACL_ENUM____4ti2_FX__SWIG_0;
int const ACL_ENUM____4ti2_FX__SWIG_0 = _4ti2_FX;
EXPORT int const ACL_ENUM____4ti2_OK__SWIG_0;
int const ACL_ENUM____4ti2_OK__SWIG_0 = _4ti2_OK;
EXPORT int const ACL_ENUM____4ti2_ERROR__SWIG_0;
int const ACL_ENUM____4ti2_ERROR__SWIG_0 = _4ti2_ERROR;
EXPORT _4ti2_state *ACL____4ti2_qsolve_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_qsolve_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_state *ACL____4ti2_rays_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_rays_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_state *ACL____4ti2_circuits_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_circuits_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_state *ACL____4ti2_zsolve_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_zsolve_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_state *ACL____4ti2_hilbert_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_hilbert_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_state *ACL____4ti2_graver_create_state__SWIG_0 (_4ti2_precision larg1) {
  _4ti2_state *lresult = (_4ti2_state *)0 ;
  _4ti2_precision arg1 ;
  _4ti2_state *result = 0 ;
  
  arg1 = larg1;
  result = (_4ti2_state *)_4ti2_graver_create_state(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_state_set_options__SWIG_0 (_4ti2_state *larg1, int larg2, char **larg3) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  int arg2 ;
  char **arg3 = (char **) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  result = (_4ti2_status)_4ti2_state_set_options(arg1,arg2,arg3);
  lresult = result;
  return lresult;
}


EXPORT void ACL____4ti2_state_delete__SWIG_0 (_4ti2_state *larg1) {
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  
  arg1 = larg1;
  _4ti2_state_delete(arg1);
}


EXPORT _4ti2_status ACL____4ti2_state_compute__SWIG_0 (_4ti2_state *larg1) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  result = (_4ti2_status)_4ti2_state_compute(arg1);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_state_create_matrix__SWIG_0 (_4ti2_state *larg1, int larg2, int larg3, char *larg4, _4ti2_matrix **larg5) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  int arg2 ;
  int arg3 ;
  char *arg4 = (char *) 0 ;
  _4ti2_matrix **arg5 = (_4ti2_matrix **) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = larg4;
  arg5 = larg5;
  result = (_4ti2_status)_4ti2_state_create_matrix(arg1,arg2,arg3,(char const *)arg4,arg5);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_state_read_matrix__SWIG_0 (_4ti2_state *larg1, char *larg2, char *larg3, _4ti2_matrix **larg4) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  _4ti2_matrix **arg4 = (_4ti2_matrix **) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = larg4;
  result = (_4ti2_status)_4ti2_state_read_matrix(arg1,(char const *)arg2,(char const *)arg3,arg4);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_state_get_matrix__SWIG_0 (_4ti2_state *larg1, char *larg2, _4ti2_matrix **larg3) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_state *arg1 = (_4ti2_state *) 0 ;
  char *arg2 = (char *) 0 ;
  _4ti2_matrix **arg3 = (_4ti2_matrix **) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  result = (_4ti2_status)_4ti2_state_get_matrix(arg1,(char const *)arg2,arg3);
  lresult = result;
  return lresult;
}


EXPORT int ACL____4ti2_matrix_get_num_rows__SWIG_0 (_4ti2_matrix *larg1) {
  int lresult = (int)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int result;
  
  arg1 = larg1;
  result = (int)_4ti2_matrix_get_num_rows((struct _4ti2_matrix const *)arg1);
  lresult = result;
  return lresult;
}


EXPORT int ACL____4ti2_matrix_get_num_cols__SWIG_0 (_4ti2_matrix *larg1) {
  int lresult = (int)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int result;
  
  arg1 = larg1;
  result = (int)_4ti2_matrix_get_num_cols((struct _4ti2_matrix const *)arg1);
  lresult = result;
  return lresult;
}


EXPORT void ACL____4ti2_matrix_write_to_stdout__SWIG_0 (_4ti2_matrix *larg1) {
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  
  arg1 = larg1;
  _4ti2_matrix_write_to_stdout((struct _4ti2_matrix const *)arg1);
}


EXPORT void ACL____4ti2_matrix_write_to_stderr__SWIG_0 (_4ti2_matrix *larg1) {
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  
  arg1 = larg1;
  _4ti2_matrix_write_to_stderr((struct _4ti2_matrix const *)arg1);
}


EXPORT void ACL____4ti2_matrix_write_to_file__SWIG_0 (_4ti2_matrix *larg1, char *larg2) {
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = larg1;
  arg2 = larg2;
  _4ti2_matrix_write_to_file((struct _4ti2_matrix const *)arg1,(char const *)arg2);
}


EXPORT _4ti2_status ACL____4ti2_matrix_set_entry_int32_t__SWIG_0 (_4ti2_matrix *larg1, int larg2, int larg3, _4ti2_int32_t *larg4) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int arg2 ;
  int arg3 ;
  _4ti2_int32_t arg4 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = *larg4;
  result = (_4ti2_status)_4ti2_matrix_set_entry_int32_t(arg1,arg2,arg3,arg4);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_matrix_get_entry_int32_t__SWIG_0 (_4ti2_matrix *larg1, int larg2, int larg3, _4ti2_int32_t *larg4) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int arg2 ;
  int arg3 ;
  _4ti2_int32_t *arg4 = (_4ti2_int32_t *) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = larg4;
  result = (_4ti2_status)_4ti2_matrix_get_entry_int32_t((struct _4ti2_matrix const *)arg1,arg2,arg3,arg4);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_matrix_set_entry_int64_t__SWIG_0 (_4ti2_matrix *larg1, int larg2, int larg3, _4ti2_int64_t *larg4) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int arg2 ;
  int arg3 ;
  _4ti2_int64_t arg4 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = *larg4;
  result = (_4ti2_status)_4ti2_matrix_set_entry_int64_t(arg1,arg2,arg3,arg4);
  lresult = result;
  return lresult;
}


EXPORT _4ti2_status ACL____4ti2_matrix_get_entry_int64_t__SWIG_0 (_4ti2_matrix *larg1, int larg2, int larg3, _4ti2_int64_t *larg4) {
  _4ti2_status lresult = (_4ti2_status)0 ;
  _4ti2_matrix *arg1 = (_4ti2_matrix *) 0 ;
  int arg2 ;
  int arg3 ;
  _4ti2_int64_t *arg4 = (_4ti2_int64_t *) 0 ;
  _4ti2_status result;
  
  arg1 = larg1;
  arg2 = larg2;
  arg3 = larg3;
  arg4 = larg4;
  result = (_4ti2_status)_4ti2_matrix_get_entry_int64_t((struct _4ti2_matrix const *)arg1,arg2,arg3,arg4);
  lresult = result;
  return lresult;
}



